In [1]:
from time import time
from datetime import datetime
import multiprocessing as mp
import numpy as np
import random
import pygame
import pickle
from pygame.locals import *
from pygame.transform import smoothscale

import logging

from settings import s, e

from agents import *
from items import *

pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
import math
import matplotlib.pyplot as plt
import numpy as np
#from sklearn . datasets import load_digits
#from sklearn import decomposition

%matplotlib inline

font = {'size'   : 12}

plt.rc('font', **font)
plt.rcParams['figure.figsize'] = (10,5)

In [3]:
arena = (np.random.rand(s.cols, s.rows) < s.crate_density).astype(int)
arena[:1, :] = -1
arena[-1:,:] = -1
arena[:, :1] = -1
arena[:,-1:] = -1
for x in range(s.cols):
    for y in range(s.rows):
        if (x+1)*(y+1) % 2 == 1:
            arena[x,y] = -1

In [4]:
arena

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1,  0,  1,  1,  1,  0,  0,  1,  0,  1,  1,  1,  0,  1,  1,  1, -1],
       [-1,  0, -1,  0, -1,  1, -1,  1, -1,  1, -1,  1, -1,  0, -1,  1, -1],
       [-1,  1,  1,  1,  1,  1,  1,  0,  0,  1,  1,  1,  1,  0,  1,  1, -1],
       [-1,  0, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1],
       [-1,  0,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1, -1],
       [-1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  0, -1,  1, -1,  1, -1],
       [-1,  0,  1,  0,  1,  1,  1,  0,  1,  1,  0,  1,  0,  1,  1,  1, -1],
       [-1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  0, -1,  1, -1],
       [-1,  1,  1,  1,  1,  1,  1,  0,  1,  0,  1,  1,  1,  1,  1,  1, -1],
       [-1,  1, -1,  0, -1,  0, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1],
       [-1,  0,  0,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  0,  1, -1],
       [-1,  0, -1,  1, -1,  1, -1,  1, -1,  1, -1,  0, -1,  1, -1,  1, -1],

In [5]:
arena[1,15]

1

In [3]:
file = open('agent_code/neo/q_table.json', 'r')
print(file)
file.close()

<_io.TextIOWrapper name='agent_code/neo/q_table.json' mode='r' encoding='cp1252'>


In [5]:
import json

In [6]:
with open('agent_code/neo/q_table.json', 'r') as json_file:
    data = json.load(json_file)

In [9]:
print(type(data))

<class 'dict'>


In [6]:
np.random.randint(0,high=(3+1))

0

In [7]:
a = [1]
a[-1]

1

In [13]:
a = np.array([1,3,5,6])
int(np.random.choice(a.shape[0], 1, replace=False))  

3

In [14]:
index

array([1])

In [18]:

np.random.choice(a)

1

In [15]:
test = [] # np.array([[2,4,1],[3,4,4]])
print(len(test))
if len(test):
    print('test')

0


In [6]:
rewards_tmp = dict()
state_string = 'test'
action = 2
curr_reward = 0.1

In [7]:
rewards_tmp[state_string] = {action: [curr_reward]}
rewards_tmp

{'test': {2: [0.1]}}

In [8]:
rewards_tmp[state_string][action].append(curr_reward)
rewards_tmp

{'test': {2: [0.1, 0.1]}}

In [7]:
a = np.array([[1,2]])
a.flatten()

array([1, 2])

In [13]:
opponent = np.array([['1','2','random_agent', '1','0']])
opponent[:, [0, 1]].flatten()

array(['1', '2'],
      dtype='<U12')

In [15]:
np.linalg.norm([13,0])

13.0